# Generated by Django 6.0.7 on 2026-07-30 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('confirmed', 'Confirmed'), ('checked_in', 'Checked In'), ('in_session', 'In Session'), ('completed', 'Completed'), ('checked_out', 'Checked Out'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20),
        ),
    ]
