# Generated by Django 6.0.7 on 2026-07-30 11:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIConfiguration',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('auto_summary_enabled', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'AI configuration',
                'verbose_name_plural': 'AI configurations',
            },
        ),
        migrations.CreateModel(
            name='ClinicConfiguration',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('facility_name', models.CharField(default='Clinic Care Medical Center', max_length=255)),
                ('address', models.TextField(blank=True, default='123 Medical Center Drive, Suite 400')),
                ('phone', models.CharField(blank=True, default='555-0100', max_length=50)),
                ('support_email', models.EmailField(blank=True, default='support@cliniccare.com', max_length=254)),
            ],
            options={
                'verbose_name': 'clinic configuration',
                'verbose_name_plural': 'clinic configurations',
            },
        ),
    ]
