# Generated by Django 6.0.7 on 2026-07-29 16:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionNote',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subjective', models.TextField(help_text='Patient symptoms, chief concern, and self-reported progress')),
                ('objective', models.TextField(help_text='Clinical observations, mental status exam, and vitals')),
                ('assessment', models.TextField(help_text='Therapist assessment, diagnosis, and progress evaluation')),
                ('plan', models.TextField(help_text='Treatment plan, interventions, homework, and next session date')),
                ('session_date', models.DateField(auto_now_add=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='session_notes', to='appointments.appointment')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_notes', to='patients.patient')),
                ('therapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'session note',
                'verbose_name_plural': 'session notes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIResult',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('SESSION_SUMMARY', 'Session Summary'), ('PROGRESS_SUMMARY', 'Progress Summary')], default='SESSION_SUMMARY', max_length=50)),
                ('model', models.CharField(default='qwen/qwen3-235b-a22b:free', max_length=100)),
                ('prompt_version', models.CharField(default='v1.0', max_length=20)),
                ('response', models.JSONField(help_text='Structured AI response JSON')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_results', to='patients.patient')),
                ('session_note', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_results', to='notes.sessionnote')),
            ],
            options={
                'verbose_name': 'AI result',
                'verbose_name_plural': 'AI results',
                'ordering': ['-created_at'],
            },
        ),
    ]
