# Generated by Django 6.0.7 on 2026-07-30 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionnote',
            name='ai_enhanced_summary',
            field=models.JSONField(blank=True, help_text='Structured AI Generated Summary JSON', null=True),
        ),
        migrations.AddField(
            model_name='sessionnote',
            name='ai_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sessionnote',
            name='ai_model_used',
            field=models.CharField(default='qwen/qwen3-235b-a22b:free', max_length=100),
        ),
        migrations.AddField(
            model_name='sessionnote',
            name='chief_complaint',
            field=models.TextField(blank=True, help_text='Primary reason for visit, symptoms, or intake concern'),
        ),
        migrations.AddField(
            model_name='sessionnote',
            name='recommendations',
            field=models.TextField(blank=True, help_text='Homework, coping strategies, and follow-up plan'),
        ),
        migrations.AddField(
            model_name='sessionnote',
            name='session_notes',
            field=models.TextField(blank=True, help_text='Clinical observations, dialogue, and session notes'),
        ),
        migrations.AddField(
            model_name='sessionnote',
            name='treatment_given',
            field=models.TextField(blank=True, help_text='Therapeutic interventions & modalities applied (e.g. CBT)'),
        ),
        migrations.AlterField(
            model_name='sessionnote',
            name='assessment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='sessionnote',
            name='objective',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='sessionnote',
            name='plan',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='sessionnote',
            name='subjective',
            field=models.TextField(blank=True, default=''),
        ),
    ]
