# Generated by Django 6.0.7 on 2026-07-30 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_sessionnote_ai_enhanced_summary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionnote',
            name='patient_response',
            field=models.TextField(blank=True, help_text='Patient engagement, insight, and response to treatment'),
        ),
        migrations.AddField(
            model_name='sessionnote',
            name='treatment_performed',
            field=models.TextField(blank=True, help_text='Specific treatment performed during session'),
        ),
    ]
