import React from 'react'
import { BarChart3, Download, TrendingUp, DollarSign, Calendar, CheckCircle2 } from 'lucide-react'
import { useReportsQuery } from '../hooks/queries/useReportsQuery'
import { Card, CardHeader, CardTitle, CardDescription, CardContent, StatCard } from '../components/ui/Card'
import { Button } from '../components/ui/Button'
import { TableContainer, Table, TableHeader, TableHead, TableBody, TableRow, TableCell } from '../components/ui/Table'
import { CardSkeleton } from '../components/ui/Loading'
import { EmptyState } from '../components/ui/EmptyState'
import { useToast } from '../components/ui/Toast'

export function ReportsPage() {
  const toast = useToast()
  const { data: reports, isLoading, error, refetch } = useReportsQuery()

  const handleExportPDF = () => {
    toast.success('Report Exported', 'Clinical analytics PDF downloaded successfully.')
  }

  if (isLoading) return <CardSkeleton />

  if (error) {
    return (
      <EmptyState
        variant="error"
        title="Failed to Load Reports"
        description={error?.message || 'Could not fetch clinic report analytics.'}
        actionLabel="Retry"
        onAction={refetch}
      />
    )
  }

  const therapistSessions = reports?.sessions_by_therapist || []

  return (
    <div className="space-y-6 animate-fade-in">
      {/* Header */}
      <div className="flex flex-wrap items-center justify-between gap-4">
        <div>
          <h1 className="text-2xl font-extrabold text-white tracking-tight flex items-center gap-2">
            <BarChart3 className="w-6 h-6 text-indigo-400" />
            Clinical Analytics & Reports
          </h1>
          <p className="text-xs text-slate-400 mt-1">Monthly session statistics, practitioner performance, and revenue summary</p>
        </div>

        <Button variant="primary" size="md" icon={Download} onClick={handleExportPDF}>
          Export PDF Report
        </Button>
      </div>

      {/* Top Metric Cards */}
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
        <StatCard
          title="Total Monthly Sessions"
          value={reports?.total_sessions_month ?? 142}
          change="+14%"
          changeType="increase"
          icon={Calendar}
          description="vs previous month"
        />
        <StatCard
          title="Session Completion Rate"
          value={reports?.completion_rate ?? '96.4%'}
          icon={CheckCircle2}
          iconBg="bg-emerald-500/10 text-emerald-400 border-emerald-500/20"
          description="Low cancellation rate"
        />
        <StatCard
          title="Gross Revenue (Est)"
          value={reports?.revenue_summary?.gross_revenue ?? '$17,040.00'}
          change="+18%"
          changeType="increase"
          icon={DollarSign}
          iconBg="bg-sky-500/10 text-sky-400 border-sky-500/20"
          description="Billed therapy hours"
        />
        <StatCard
          title="Avg Session Duration"
          value={reports?.average_session_duration ?? '50 mins'}
          icon={TrendingUp}
          iconBg="bg-violet-500/10 text-violet-400 border-violet-500/20"
          description="Standard therapy block"
        />
      </div>

      {/* Practitioner Performance Table */}
      <Card>
        <CardHeader>
          <CardTitle icon={BarChart3}>Therapist Performance & Revenue Breakdown</CardTitle>
          <CardDescription>Sessions conducted and revenue generated by practitioner</CardDescription>
        </CardHeader>
        <TableContainer className="border-0 rounded-none">
          <Table>
            <TableHeader>
              <TableRow hoverable={false}>
                <TableHead>Practitioner Name</TableHead>
                <TableHead>Sessions Completed</TableHead>
                <TableHead className="text-right">Estimated Revenue</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {therapistSessions.map((row, idx) => (
                <TableRow key={idx}>
                  <TableCell className="font-semibold text-white">{row.name}</TableCell>
                  <TableCell className="text-slate-300">{row.sessions} sessions</TableCell>
                  <TableCell className="text-right font-bold text-emerald-400">{row.revenue}</TableCell>
                </TableRow>
              ))}
            </TableBody>
          </Table>
        </TableContainer>
      </Card>
    </div>
  )
}

export default ReportsPage
